# Generated by Django 3.1.7 on 2021-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasl_app', '0002_auto_20210313_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userId', models.BigIntegerField()),
                ('id', models.BigIntegerField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
