# Generated by Django 3.1.7 on 2021-03-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasl_app', '0003_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='PizzaModel',
        ),
    ]
